/**
 * The disclosure. Not fine print, not dismissible, not configurable.
 *
 * The recruiter is told before any content that this is an AI representation of a real
 * person. PRD §12.6. If a future change makes this removable, that change is wrong.
 */

class DisclosureBadge extends HTMLElement {
  connectedCallback() {
    const compact = this.hasAttribute('compact');
    this.className = compact
      ? 'block text-xs text-muted leading-relaxed'
      : 'block rounded-lg border border-paper/10 bg-panel/60 p-3 text-xs text-muted leading-relaxed';
    this.innerHTML = `
      <p>
        <strong class="text-paper/80">This is an AI representation of Kshitij Tripathi.</strong>
        The face and voice are his, recorded with his consent. Answers are generated by a
        language model from his published resume, and every factual answer is cited.
        He is a real person — <a class="underline hover:text-paper" href="mailto:kttripathi317@gmail.com">kttripathi317@gmail.com</a>.
      </p>`;
  }
}

customElements.define('disclosure-badge', DisclosureBadge);
